services:
  mysql:
    image: mysql:8.0
    container_name: mysql_dev
    restart: unless-stopped
    ports:
      - "${MYSQL_PUBLIC_PORT}:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      # MYSQL_USER: ${MYSQL_USER}
      # MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - mysql_data:/var/lib/mysql
      # image mysql:8.0 auto run /docker-entrypoint-initdb.d/*.sql when init, but now we use prisma instead
      # - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
    command: --default-authentication-plugin=mysql_native_password
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s

  backend:
    image: minhnhat1104/backend:dev
    container_name: backend_dev
    build:
      context: ./
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "8000:8000"
    environment:
      NODE_ENV: development
    env_file:
      - ./.env
    depends_on:
      mysql: # quyết định thứ tự start container
        condition: service_healthy
        restart: true

    volumes:
      - ./:/app # 2-way bind with folder /app in Container
      - upload:/app/src/upload
      - cache:/app/src/cache
      - /app/node_modules # anonymous volume, ko bind mount với máy thực
    command: sh -c "npx prisma migrate dev --name init && npx prisma generate && npm run dev" # create a shell and run command

volumes:
  mysql_data: # declare Docker volume (1 folder)
  upload: # declare Docker volume (1 folder)
  cache:
